# Generated by Django 5.2.7 on 2025-11-16 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(choices=[('FUTBOL', 'Futbol'), ('BASQUETBALL', 'Basquetball'), ('VOLEYBALL', 'Voleyball'), ('TENIS', 'Tenis'), ('RUGBY', 'Rugby'), ('HANDBALL', 'Handball'), ('BOWLING', 'Bowling'), ('SQUASH', 'Squash'), ('PADEL', 'Padel'), ('OTRO', 'Otro'), ('---', '---')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('estacionamiento_disponible', models.BooleanField(default=False)),
                ('camarines_disponible', models.BooleanField(default=False)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='cuentas.dueno')),
            ],
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('superficie', models.CharField(choices=[('PASTO_NATURAL', 'Pasto Natural'), ('PASTO_SINTETICO', 'Pasto Sintético'), ('CEMENTO', 'Cemento'), ('ARCILLA', 'Arcilla'), ('MADERA', 'Madera'), ('CAUCHO', 'Caucho'), ('VINILO', 'Vinilo')], max_length=25)),
                ('iluminacion', models.CharField(max_length=20)),
                ('interior', models.BooleanField()),
                ('valor_por_bloque', models.DecimalField(decimal_places=0, max_digits=10)),
                ('deporte', models.ManyToManyField(related_name='canchas', to='establecimientos.deporte')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='establecimientos.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sabado'), ('DOMINGO', 'Domingo')], max_length=20, unique=True)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='establecimientos.establecimiento')),
            ],
        ),
    ]
