# Generated by Django 5.2.7 on 2025-12-03 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('FUTBOL', 'Futbol'), ('BASQUETBALL', 'Basquetball'), ('VOLEYBALL', 'Voleyball'), ('TENIS', 'Tenis'), ('RUGBY', 'Rugby'), ('HANDBALL', 'Handball'), ('BOWLING', 'Bowling'), ('SQUASH', 'Squash'), ('PADEL', 'Padel'), ('OTRO', 'Otro'), ('---', '---')], default='---', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('estacionamiento_disponible', models.BooleanField(default=False)),
                ('camarines_disponible', models.BooleanField(default=False)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='cuentas.dueno')),
            ],
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(choices=[('Futbol', 'Futbol'), ('Basquetball', 'Basquetball'), ('Voleyball', 'Voleyball'), ('Tenis', 'Tenis'), ('Rugby', 'Rugby'), ('Handball', 'Handball'), ('Bowling', 'Bowling'), ('Squash', 'Squash'), ('Padel', 'Padel'), ('Otro', 'Otro'), ('---', '---')], default='---', max_length=20)),
                ('nombre', models.CharField(max_length=25)),
                ('superficie', models.CharField(choices=[('Pasto_Natural', 'Pasto Natural'), ('Pasto_Sintético', 'Pasto Sintético'), ('Cemento', 'Cemento'), ('Arcilla', 'Arcilla'), ('Madera', 'Madera'), ('Caucho', 'Caucho'), ('Vinilo', 'Vinilo')], max_length=25)),
                ('iluminacion', models.CharField(choices=[('LED', 'LED'), ('Fluorecente', 'Fluorecente'), ('Natural', 'Natural'), ('Halogena', 'Halogena'), ('Mixta', 'Mixta')], max_length=20)),
                ('interior', models.BooleanField(default=False)),
                ('valor_por_bloque', models.DecimalField(decimal_places=0, max_digits=10)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='establecimientos.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=20)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='establecimientos.establecimiento')),
            ],
        ),
    ]
