# Generated by Django 5.2.7 on 2025-11-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='deporte',
        ),
        migrations.DeleteModel(
            name='Deporte',
        ),
        migrations.AddField(
            model_name='cancha',
            name='deporte',
            field=models.CharField(choices=[('FUTBOL', 'Futbol'), ('BASQUETBALL', 'Basquetball'), ('VOLEYBALL', 'Voleyball'), ('TENIS', 'Tenis'), ('RUGBY', 'Rugby'), ('HANDBALL', 'Handball'), ('BOWLING', 'Bowling'), ('SQUASH', 'Squash'), ('PADEL', 'Padel'), ('OTRO', 'Otro'), ('---', '---')], default='---', max_length=20),
        ),
    ]
