# Generated by Django 5.2.7 on 2025-12-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='iluminacion',
            field=models.CharField(choices=[('Halogena', 'Halogena'), ('Fluorecente', 'Fluorecente'), ('Natural', 'Natural'), ('LED', 'LED'), ('Mixta', 'Mixta')], max_length=20),
        ),
    ]
