# Generated by Django 5.2.7 on 2025-11-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0002_remove_cancha_deporte_delete_deporte_cancha_deporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cancha',
            name='deporte',
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='deporte',
            field=models.ManyToManyField(related_name='canchas', to='establecimientos.deporte'),
        ),
    ]
