# Generated by Django 5.2.7 on 2025-12-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0002_alter_cancha_iluminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='iluminacion',
            field=models.CharField(choices=[('Halogena', 'Halogena'), ('LED', 'LED'), ('Fluorecente', 'Fluorecente'), ('Natural', 'Natural'), ('Mixta', 'Mixta')], max_length=20),
        ),
    ]
