# Generated by Django 5.2.7 on 2025-11-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0003_deporte_remove_cancha_deporte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deporte',
            name='deporte',
        ),
        migrations.AddField(
            model_name='deporte',
            name='nombre',
            field=models.CharField(choices=[('FUTBOL', 'Futbol'), ('BASQUETBALL', 'Basquetball'), ('VOLEYBALL', 'Voleyball'), ('TENIS', 'Tenis'), ('RUGBY', 'Rugby'), ('HANDBALL', 'Handball'), ('BOWLING', 'Bowling'), ('SQUASH', 'Squash'), ('PADEL', 'Padel'), ('OTRO', 'Otro'), ('---', '---')], default='---', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='horarioestablecimiento',
            name='dia',
            field=models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sabado'), ('DOMINGO', 'Domingo')], max_length=20),
        ),
    ]
