# Generated by Django 5.2.7 on 2025-11-27 04:09

import establecimientos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0004_remove_deporte_deporte_deporte_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='deporte',
        ),
        migrations.AddField(
            model_name='cancha',
            name='deporte',
            field=models.CharField(choices=[('FUTBOL', 'Futbol'), ('BASQUETBALL', 'Basquetball'), ('VOLEYBALL', 'Voleyball'), ('TENIS', 'Tenis'), ('RUGBY', 'Rugby'), ('HANDBALL', 'Handball'), ('BOWLING', 'Bowling'), ('SQUASH', 'Squash'), ('PADEL', 'Padel'), ('OTRO', 'Otro'), ('---', '---')], default='---', max_length=30, verbose_name=establecimientos.models.Deporte),
        ),
    ]
