# Generated by Django 5.2.7 on 2025-11-27 04:15

import establecimientos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0006_alter_deporte_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='deporte',
            field=models.CharField(choices=[('FUTBOL', 'Futbol'), ('BASQUETBALL', 'Basquetball'), ('VOLEYBALL', 'Voleyball'), ('TENIS', 'Tenis'), ('RUGBY', 'Rugby'), ('HANDBALL', 'Handball'), ('BOWLING', 'Bowling'), ('SQUASH', 'Squash'), ('PADEL', 'Padel'), ('OTRO', 'Otro'), ('---', '---')], default='---', verbose_name=establecimientos.models.Deporte),
        ),
    ]
