# Generated by Django 5.2.7 on 2025-11-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0007_alter_cancha_deporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='deporte',
        ),
        migrations.AlterField(
            model_name='cancha',
            name='iluminacion',
            field=models.CharField(choices=[('NATURAL', 'Natural'), ('HALOGENA', 'Halogena'), ('FLUORECESENTE', 'Fluorecente'), ('LED', 'LED'), ('MIXTA', 'Mixta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='interior',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='nombre',
            field=models.CharField(choices=[('FUTBOL', 'Futbol'), ('BASQUETBALL', 'Basquetball'), ('VOLEYBALL', 'Voleyball'), ('TENIS', 'Tenis'), ('RUGBY', 'Rugby'), ('HANDBALL', 'Handball'), ('BOWLING', 'Bowling'), ('SQUASH', 'Squash'), ('PADEL', 'Padel'), ('OTRO', 'Otro'), ('---', '---')], default='---', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='deporte',
            field=models.ManyToManyField(choices=[('FUTBOL', 'Futbol'), ('BASQUETBALL', 'Basquetball'), ('VOLEYBALL', 'Voleyball'), ('TENIS', 'Tenis'), ('RUGBY', 'Rugby'), ('HANDBALL', 'Handball'), ('BOWLING', 'Bowling'), ('SQUASH', 'Squash'), ('PADEL', 'Padel'), ('OTRO', 'Otro'), ('---', '---')], default='---', to='establecimientos.deporte'),
        ),
    ]
