# Generated by Django 5.2.7 on 2025-11-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0008_remove_cancha_deporte_alter_cancha_iluminacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='deporte',
        ),
        migrations.AlterField(
            model_name='cancha',
            name='iluminacion',
            field=models.CharField(choices=[('LED', 'LED'), ('FLUORECESENTE', 'Fluorecente'), ('MIXTA', 'Mixta'), ('NATURAL', 'Natural'), ('HALOGENA', 'Halogena')], max_length=20),
        ),
        migrations.AddField(
            model_name='cancha',
            name='deporte',
            field=models.CharField(choices=[('FUTBOL', 'Futbol'), ('BASQUETBALL', 'Basquetball'), ('VOLEYBALL', 'Voleyball'), ('TENIS', 'Tenis'), ('RUGBY', 'Rugby'), ('HANDBALL', 'Handball'), ('BOWLING', 'Bowling'), ('SQUASH', 'Squash'), ('PADEL', 'Padel'), ('OTRO', 'Otro'), ('---', '---')], default='---', max_length=20),
        ),
    ]
