# Generated by Django 5.2.7 on 2025-11-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0009_remove_cancha_deporte_alter_cancha_iluminacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='iluminacion',
            field=models.CharField(choices=[('LED', 'LED'), ('MIXTA', 'Mixta'), ('HALOGENA', 'Halogena'), ('NATURAL', 'Natural'), ('FLUORECESENTE', 'Fluorecente')], max_length=20),
        ),
    ]
