# Generated by Django 5.2.7 on 2025-11-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0010_alter_cancha_iluminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='iluminacion',
            field=models.CharField(choices=[('FLUORECESENTE', 'Fluorecente'), ('MIXTA', 'Mixta'), ('HALOGENA', 'Halogena'), ('LED', 'LED'), ('NATURAL', 'Natural')], max_length=20),
        ),
    ]
