# Generated by Django 5.2.7 on 2025-11-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0011_alter_cancha_iluminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='iluminacion',
            field=models.CharField(choices=[('FLUORECESENTE', 'Fluorecente'), ('MIXTA', 'Mixta'), ('NATURAL', 'Natural'), ('LED', 'LED'), ('HALOGENA', 'Halogena')], max_length=20),
        ),
    ]
