# Generated by Django 5.2.7 on 2025-12-01 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_invitation'),
        ('reservas', '0002_alter_reserva_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='reservas.reserva'),
        ),
    ]
