# Generated by Django 5.2.7 on 2025-11-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
