# Generated by Django 5.2.7 on 2025-12-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0003_alter_cancha_iluminacion'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cancha',
            field=models.ForeignKey(default='---', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='establecimientos.cancha'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('TERMINADA', 'Terminada'), ('EN_CURSO', 'En Curso')], default='PENDIENTE', max_length=20),
        ),
    ]
